Hemer Jan, Pavlovský Jakub
# Prove of concept
---
This code serves as a proof of feasibility of the project. We have succesfully managed to scrape data from the *www.fortunaliga.cz* webiste for 2022/23 football season. this is not the whole dataset as multiple other seasons will be also scraped and merged to the dataset, using a similar method.

In [2]:
package_names = ['requests', 'bs4', 'pandas']
import subprocess
import sys

def ensure_packages_are_installed(package_names):
    for package_name in package_names:
        try:
            # Try to import the package
            __import__(package_name)
            print(f"{package_name} is already installed.")
        except ImportError:
            # If the package is not installed, install it
            print(f"{package_name} not found, installing...")
            subprocess.check_call([sys.executable, "-m", "pip", "install", package_name])
            print(f"{package_name} has been installed.")

# Ensure all specified packages are installed
ensure_packages_are_installed(package_names)

numpy is already installed.
pandas is already installed.
scikit-learn not found, installing...
Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.4.0-1-cp39-cp39-macosx_12_0_arm64.whl (10.7 MB)
Requirement already satisfied: scipy>=1.6.0 in /Users/jenda/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (1.11.3)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Requirement already satisfied: numpy<2.0,>=1.19.5 in /Users/jenda/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (1.25.0)
Collecting joblib>=1.2.0
  Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn
Successfully installed joblib-1.3.2 scikit-learn-1.4.0 threadpoolctl-3.2.0
scikit-learn has been installed.

WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

#If you don't have these packages installed, please install it, otherwise it won't work

/Users/jenda/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [101]:
list_number1 = ['150', '0', '50', '50', '150', '200', '250']
list_number2 = ['0', '50', '100', '150', '200', '250', '300']
col_names = ['Zápas', 'G', 'G1p', 'G2p', 'ÚT', 'GR', 'S', 'SnB', 'P', 'P%', 'ŽK', 'ČK', 'F']
merged_df = pd.DataFrame(columns = col_names)

for yea in range(2014, 2025):
    for ln1, ln2 in zip(list_number1, list_number2):
        response = requests.get(f"https://www.fortunaliga.cz/statistiky?unit=4&status=&parameter=1&season={yea}&club=0&game_limit=&nationality=&age=&position=&list_number={ln1}&order=2&order_dir=1&list_number={ln2}")
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            table = soup.find('table', class_ = 'table')
        
            titles = soup.find_all('abbr')
            titles = [element.text for element in titles]

            content = table.find_all('tr')
            #print(type(content))
            content = [table.find_all('td') for element in content]
            content = [str(element.text) for result_set in content for element in result_set]
            #print(type(content))

            num_elements_per_row = 14
            num_rows = len(content) // num_elements_per_row
            rows = [content[i:i + num_elements_per_row] for i in range(0, len(content), num_elements_per_row)]
            df = pd.DataFrame(rows, columns = [f'Column_{i+1}' for i in range(num_elements_per_row)])
            df = df.set_index('Column_1')
            df.columns = titles
            df = df.reset_index()
            df = df.drop_duplicates(subset = ['Column_1'])

            merged_df = pd.concat([merged_df, df], axis = 0, ignore_index = True)

In [108]:
merged_df.tail()

,Zápas,G,G1p,G2p,ÚT,GR,S,SnB,P,P%,ŽK,ČK,F,Column_1
2729,"SLA-TEP 0:7, 13/14",7,2,5,140,7,34,11,822,"76,3%",7,1,28,236.
2730,"OLO-JIH 4:3, 13/14",7,2,5,167,1,36,17,842,"75,7%",6,0,28,237.
2731,"MBL-BRN 5:2, 13/14",7,4,3,160,3,29,16,821,"80,6%",1,0,26,238.
2732,"PLZ-FKJ 6:1, 13/14",7,4,3,157,5,38,13,731,"85,0%",7,1,32,239.
2733,"FKJ-ZNO 5:5, 13/14",10,4,6,163,0,38,17,856,"80,7%",7,0,32,240.